collections:
  # ==========================================
  # Challenge Manager
  # ==========================================
  - name: "challenge"
    label: "Challenge Manager"
    files:
      - name: "challenge_data"
        label: "Challenge Progress"
        file: "data/challenges.json"
        fields:
          - label: "Challenge Items"
            name: "aws_challenge"
            widget: "list"
            summary: "Day {{fields.day}} - {{fields.title}}"
            fields:
              - {label: "Day", name: "day", widget: "string", hint: "e.g., Day 1, Day 2"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Status", name: "status", widget: "select", options: ["completed", "in-progress", "locked"], default: "locked"}
              - {label: "Description", name: "description", widget: "text", required: false}
              - {label: "Date Completed", name: "completedDate", widget: "datetime", required: false}

 