# Pages CMS Configuration
# Repository: mohammadzfaisal/myterminalGUI

# Media configuration
media:
  input: static/images
  output: /images

# Content collections
content:
  # Projects Manager
  - name: projects
    label: Projects
    type: file
    path: data/data.json
    format: json
    view:
      primary: title
    fields:
      - name: projects
        label: Projects
        type: object
        list: true
        fields:
          - name: id
            label: ID
            type: string
          - name: title
            label: Title
            type: string
          - name: description
            label: Description
            type: text
          - name: icon
            label: Icon
            type: string
          - name: github
            label: GitHub URL
            type: string
          - name: demo
            label: Demo URL
            type: string
          - name: featured
            label: Featured
            type: boolean
          - name: badges
            label: Badges
            type: object
            list: true
            fields:
              - name: name
                label: Name
                type: string
              - name: color
                label: Color
                type: string

  # Blog Posts Manager
  - name: blogs
    label: Blog Posts
    type: file
    path: data/data.json
    format: json
    view:
      primary: title
    fields:
      - name: blogs
        label: Blog Posts
        type: object
        list: true
        fields:
          - name: id
            label: ID
            type: string
          - name: title
            label: Title
            type: string
          - name: date
            label: Date
            type: date
          - name: category
            label: Category
            type: string
          - name: description
            label: Description
            type: text

  # AWS Challenge Manager
  - name: challenge
    label: Challenge Manager
    type: file
    path: data/data.json
    format: json
    view:
      primary: title
    fields:
      - name: aws_challenge
        label: Challenge Items
        type: object
        list: true
        fields:
          - name: day
            label: Day
            type: string
          - name: title
            label: Title
            type: string
          - name: status
            label: Status
            type: select
            options:
              values:  # <-- This is the key you were missing!
                - value: completed
                  label: Completed
                - value: in progress
                  label: In Progress
                - value: locked
                  label: Locked

  # What I Do (Services)
  - name: about_services
    label: What I Do
    type: file
    path: data/data.json
    format: json
    view:
      primary: title
    fields:
      - name: about_services
        label: Services
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
          - name: description
            label: Description
            type: text

  # Certifications
  - name: about_certifications
    label: Certifications
    type: file
    path: data/data.json
    format: json
    view:
      primary: title
    fields:
      - name: about_certifications
        label: Certifications
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
          - name: provider
            label: Provider
            type: string
          - name: year
            label: Year
            type: string
          - name: group
            label: Group
            type: string

  # Skills
  - name: about_skills
    label: Skills
    type: file
    path: data/data.json
    format: json
    view:
      primary: category
    fields:
      - name: about_skills
        label: Skills
        type: object
        list: true
        fields:
          - name: category
            label: Category
            type: string
          - name: skills
            label: Skills
            type: string
          - name: group
            label: Group
            type: string

  # About Page Content
  - name: about
    label: About Page
    type: file
    path: content/about/_index.md
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: body
        label: Body
        type: rich-text

  # Cloud Roadmap Manager
  - name: roadmap
    label: Cloud Roadmap
    type: file
    path: data/data.json
    format: json
    view:
      primary: title
    fields:
      - name: cloud_roadmap
        label: Roadmap Phases
        type: object
        list: true
        fields:
          - name: phase
            label: Phase Number
            type: number
          - name: title
            label: Phase Title
            type: string
          - name: description
            label: Phase Description
            type: text
          - name: topics
            label: Topics
            type: object
            list: true
            fields:
              - name: name
                label: Topic Name
                type: string
              - name: skills
                label: Skills
                type: string
                list: true
              - name: resources
                label: Learning Resources
                type: string
                list: true
              - name: tags
                label: Tags (for blog post matching)
                type: string
                list: true

# Global settings
settings:
  content:
    merge: true
